### ISSUE TITLE
Latest release crashes when pushing shuffle

### ISSUE THREAD

**Issue by organman91** [TruthNZ/DominionShuffle#12]
Clearing the cache and storage for the app does not seem to solve the issue. Android 13, device is Pixel 6a.

**Comment by TruthNZ** [comment]
Thanks for the report.

There is a fixed version currently going through Google's review process
now.

Hopefully it'll be updated very soon.

**Comment by TruthNZ** [comment]
Fixed in 3d7e054d00c60b10a8c58c9bfd9d7477a78fd646 and #11
