### ISSUE TITLE
Add Cards From 2nd Ed. of Dominion/Intrigue, and Sauna/Avanto

### ISSUE THREAD

**Issue by MattArnold** [TruthNZ/DominionShuffle#3]
Base Set, 2nd Edition:
Harbinger $3 Action
Merchant $3 Action
Vassal $3 Action
Poacher $4 Action
Bandit $5 Action
Sentry $5 Action
Artisan $6 Action

Base Set, 1st Edition Only:
Chancellor, Woodcutter, Feast, Spy, Thief, Adventurer

Intrigue, 2nd Edition:
Lurker $2 Action
Diplomat $4 Action / Reaction
Mill $4 Action / Victory
Secret Passage $4 Action
Courtier $5 Action
Patrol $5 Action
Replace $5 Action / Attack

Intrigue, 1st Edition Only:
Secret Chamber, Great Hall, Coppersmith, Scout, Saboteur, Tribute

2016 Promo Card:
Sauna $4 Action / Avanto $5 Action (dual stack mechanic from Empires)

**Comment by TruthNZ** [comment]
2nd Edition cards have already been added.

**Comment by TruthNZ** [comment]
Sauna/Avanto added - new version 1.15.1 just uploaded to Google Play.
