### ISSUE TITLE
How do I exclude specific cards and add specific promo cards?

### ISSUE THREAD

**Issue by timur-tabi** [TruthNZ/DominionShuffle#5]
I just can't figure out how to do this.  I want to be able to do two things:

1. Exclude specific cards from various sets.  These are "banned" cards in my games because no one likes them.

2. Specify individual promo cards.

Also, what is the difference between the "red minus" option and just having a grey dot?  Don't they just both mean, "do not include this set?"

**Comment by gw1108** [comment]
In the SELECT tab of Dominion shuffle is where you specify what dominion sets you own. You can also specify which cards you own or do not own.
1. In the select tab click the specific cards so they show up as minus. Now dominion shuffle will treat it as if you do not own that card and it's effectively banned.
2. In the select tab click Promo or scroll down to promo and select the individual promo cards that you own with a +.
3. A grey dot means you do not own the card/set. A red minus means you want to override the card as a not owned card. IE. A red dot in spy but a green + in Base Set 1st Edition means you want to select all cards in the Base Set 1st Edition except spy.

**Comment by TruthNZ** [comment]
Roughly as per gw1108 said.

For your case, make sure your banned cards have red minus's next to them.
For the individual Promos you want to have in your possible draw pile, make
sure they have green plus's next to them - but the Promo Group is set to a
grey dot.


If you want the exact details:

A green plus on a card means alway include that card in your master deck.
A red minus on a card means never include that card in your master deck.
A grey dot on a card means don't specifically include this card in your
master deck - but it might be included if you've included (green plus) a
group which includes that card.

A green plus on a group means include all the cards in that group in your
master deck , unless they are also in a red minus group, or have a red
minus on the specific card.
A red minus on a group means never include cards from that set in your
master deck, even if they are in another included (green plus)  group. But
a green plus card will still be included even if it was in this group. The
only difference between a red minus and a grey dot on a group, is if any of
the cards overlap with another group.
A grey dot on a group means don't specifically include this group in your
master deck - but cards in it will be included if you've included them
specifically (green plus), or they're part of another group you've included
(green plus).

(This all applies to the SELECT tab - which is just for selecting the
master deck of cards to draw from)

Gynn Rickerby
Cell: +64 21 262 5205
There is no religion higher than the Truth.

**Comment by timur-tabi** [comment]
Ok, thanks.  My confusion was that I didn't realize I had to scroll all the way down to see individual cards.
